const mongoose = require('mongoose');

// Sub-schema for individual daily challenges within a track
const dailySparkSchema = new mongoose.Schema({
    day: {
        type: Number,
        required: true
    },
    title: {
        type: String,
        required: true,
        trim: true
    },
    description: {
        type: String,
        required: true,
        trim: true
    },
    status: {
        type: String,
        enum: ['Locked', 'Active', 'Completed', 'Skipped'],
        default: 'Locked'
    },
    // Stores the Cloudinary URL of their video proof once uploaded
    videoSubmissionUrl: {
        type: String,
        default: null
    },
    completedAt: {
        type: Date,
        default: null
    }
}, { _id: false }); // Prevents Mongoose from generating unnecessary nested IDs for every single day

// Main schema for the personalized learning path
const sparkTrackSchema = new mongoose.Schema({
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
        index: true // Indexed for fast lookups when loading a user's feed/dashboard
    },
    topic: {
        type: String,
        required: true,
        trim: true
    },
    difficulty: {
        type: String,
        enum: ['Beginner', 'Intermediate', 'Advanced'],
        required: true
    },
    totalDays: {
        type: Number,
        required: true,
        min: 1,
        max: 30 // Safe guard to prevent massive AI token usage
    },
    currentDay: {
        type: Number,
        default: 1
    },
    isCompleted: {
        type: Boolean,
        default: false
    },
    // Track continuous engagement specifically for this learning track
    currentStreak: {
        type: Number,
        default: 0
    },
    // Used by backend cron-jobs to determine if a streak has broken (e.g., missed > 24 hours)
    lastActivityAt: {
        type: Date,
        default: Date.now
    },
    // The complete array generated by the Gemini AI
    roadmap: [dailySparkSchema]
}, {
    timestamps: true // Automatically creates `createdAt` and `updatedAt` fields
});

// Compound index: A user can only have ONE active track at a time for a specific topic
sparkTrackSchema.index({ userId: 1, topic: 1 });

const SparkTrack = mongoose.model('SparkTrack', sparkTrackSchema);
module.exports = SparkTrack;